[package]
name = "learn-hyper"
version = "0.1.0"
authors = ["George T. C. Lai <tsungchih.hd@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
hyper = "0.12"
log = "0.4"
pretty_env_logger = "0.3"